export const SET_POSTS = 'SET_POSTS';
export const SET_CURRENT_POST = 'SET_CURRENT_POST';
export const SET_POSTS_PAGINATION = 'SET_POSTS_PAGINATION';

export default {
  SET_POSTS,
  SET_POSTS_PAGINATION,
  SET_CURRENT_POST,
};
